### ISSUE TITLE
Three Incorrect JSDoc Parameters in Asserters

### ISSUE THREAD

**Issue by mikedpad** [portabletext/toolkit#3]
This issue isn't critical. It wasn't breaking my build in SvelteKit, but it would generate three annoying warning / hints.

In the [asserters.ts](https://github.com/portabletext/toolkit/blob/main/src/asserters.ts) file, there are three incorrectly named parameters that's causing a warning to be thrown when using SvelteKit's `check` script.

1. [`node` should be `block`](https://github.com/portabletext/toolkit/blob/b4caa048fb0df69809d131f5eb2532189c3ccca9/src/asserters.ts#L59)
2. [`block` should be `span`](https://github.com/portabletext/toolkit/blob/b4caa048fb0df69809d131f5eb2532189c3ccca9/src/asserters.ts#L90)
3. [`block` should be `node`](https://github.com/portabletext/toolkit/blob/b4caa048fb0df69809d131f5eb2532189c3ccca9/src/asserters.ts#L103)

Nothing complicated as a rename stops the suggested warning / hint from being logged.

**Comment by rexxars** [comment]
Thanks for reporting and for the PR!

**Comment by rexxars** [comment]
Released your fix in v1.0.6
